### ISSUE TITLE
Paths in project

### ISSUE THREAD

**Issue by dimdieo** [sibutrip/MixWarp#1]
Hello! 

Thank you very much for this project, for a long time I could not launch LIBPD in SWIFTUI.

Now everything works fine, but there is a small problem with the paths. I have Sound and Abstraction folders in my project, but xCode does not see them, although everything works fine in Pure Data. If I move the files to the root of the project, everything also works fine. But I need to place files in folders, there is a rather complicated folder structure.

Could you tell me how to use paths in the project?

**Comment by sibutrip** [comment]
Hey there! I added LibPD to my xcode project using cocoapods. So I manage the two projects through an xcworkspace file. If you have that set up, check out the PDPatch.m and PDPatch.h files as well as the AudioTest.pd file. I specify the paths to each PD object in AudioTest.pd. In the .m and .h files I also specify the inputs and outputs using the PdBase wrapper in the libpd API. Let me know if this is helpful! good luck

**Comment by dimdieo** [comment]
Thanks for the advice, I'm finally figuring this out.  Everything is working well now
